volumes:
  test-database-data:

networks:
  integration-stack:
    name: integration-stack
    external: false

services:
  # Integration Test Database
  test-database:
    container_name: test-database
    image: postgres
    restart: always
    volumes:
      - test-database-data:/var/lib/postgresql/data/
    env_file: .env
    networks:
      - integration-stack
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  # Test Runner Service (Playwright for E2E Tests)
  test-runner:
    image: mcr.microsoft.com/playwright:v1.50.1-jammy
    container_name: test-runner
    depends_on:
      - test-database
    volumes:
      - .:/tests  # Mount the entire project
    working_dir: /tests  # Ensure correct working directory
    networks:
      - integration-stack
    environment:
      - NODE_ENV=integration  # Set environment variable for tests
    command: [ "sh", "-c", "yarn install && yarn db-seed && yarn test-e2e" ]
