name: JMeter Performance Test

on:
  push:
    branches:
      - main  # Run only after a PR is merged into main

jobs:
  performance-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4  # Latest version

      - name: Install JMeter
        run: |
          sudo apt update
          sudo apt install -y openjdk-11-jre

          # Get the latest JMeter version dynamically
          JMETER_VERSION=$(curl -s https://jmeter.apache.org/download_jmeter.cgi | grep -oP 'apache-jmeter-\K[0-9]+\.[0-9]+\.[0-9]+' | head -1)
          echo "Latest JMeter Version: $JMETER_VERSION"

          # Download and extract JMeter
          wget "https://dlcdn.apache.org/jmeter/binaries/apache-jmeter-${JMETER_VERSION}.tgz"
          tar -xzf "apache-jmeter-${JMETER_VERSION}.tgz"
          mv "apache-jmeter-${JMETER_VERSION}" jmeter
          echo "$(pwd)/jmeter/bin" >> $GITHUB_PATH

      - name: Ensure JMeter Report Directory Exists
        run: |
          mkdir -p tests/jmeter/report
          chmod -R 777 tests/jmeter  # Ensure GitHub Actions can write files

      - name: Run JMeter Test
        run: |
          jmeter/bin/jmeter -n -t tests/calcom.jmx -l tests/jmeter/results.jtl -e -o tests/jmeter/report

      - name: Upload JMeter Report
        uses: actions/upload-artifact@v4
        with:
          name: jmeter-report
          path: tests/jmeter/report
