name: JMeter Performance Test

on:
  push:
    branches:
      - main  # Run only after a PR is merged into main

jobs:
  performance-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4  # Use the latest version

      - name: Install JMeter
        run: |
          sudo apt update
          sudo apt install -y openjdk-11-jre
          wget https://downloads.apache.org//jmeter/binaries/apache-jmeter-5.6.2.tgz
          tar -xzf apache-jmeter-5.6.2.tgz
          mv apache-jmeter-5.6.2 jmeter
          echo "$(pwd)/jmeter/bin" >> $GITHUB_PATH

      - name: Run JMeter Test
        run: |
          jmeter/bin/jmeter -n -t tests/calcom.jmx -l tests/jmeter/results.jtl -e -o tests/jmeter/report

      - name: Upload JMeter Report
        uses: actions/upload-artifact@v4  # Updated to v4
        with:
          name: jmeter-report
          path: tests/jmeter/report
