name: Lighthouse Audit

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Lighthouse CI
        run: npm install -g @lhci/cli@latest

      - name: Create Report Directory
        run: mkdir -p lhci_reports

      - name: Run Lighthouse Audit
        run: |
          lhci autorun --collect.url=https://example.com \
            --upload.target=filesystem \
            --upload.outputDir=./lhci_reports \
            --collect.settings.output=html || echo "Lighthouse audit completed with warnings"

      - name: Debug - Check Files
        run: ls -lR

      - name: Upload Lighthouse Report
        uses: actions/upload-artifact@v4
        with:
          name: lighthouse-report
          path: lhci_reports
